micronaut:
  application:
    name: nfcwalker
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET}
    oauth2:
      clients:
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
          openid:
            enabled: true
          scopes:
            - openid
            - email
            - profile
          endpoints:
            authorization: https://accounts.google.com/o/oauth2/v2/auth
            token: https://oauth2.googleapis.com/token
            jwks: https://www.googleapis.com/oauth2/v3/certs
  openapi:
    enabled: true
  email:
    from:
      email: ${MAIL_FROM}
      name: ${APP_NAME}

javamail:
  properties:
    mail.transport.protocol: smtp
    mail.smtp.host: ${SMTP_HOST}
    mail.smtp.port: ${SMTP_PORT}
    mail.smtp.auth: ${SMTP_AUTH}
    mail.smtp.starttls.enable: ${SMTP_STARTTLS}
  authentication:
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}

datasources:
  default:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    maximum-pool-size: 3

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: false
        format_sql: false

flyway:
  datasources:
    default:
      enabled: true

mail:
  smtp:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    auth: ${SMTP_AUTH}
    from: ${MAIL_FROM}

app:
  name: ${APP_NAME}
  frontend-url: ${FRONTEND_URL}
  email:
    default-language: ${APP_EMAIL_DEFAULT_LANGUAGE:en}
  challenge:
    secret: ${APP_CHALLENGE_SECRET}
    ttl-seconds: 60
